version: '3.9'

services:

  postgres-dev:
    image: postgres
    container_name: postgres-dev
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=dev_database
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
  postgres-test:
    image: postgres
    container_name: postgres-test
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=test_database
    ports:
      - "5433:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
  redis:
    container_name: redis-cache
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  postgres-dev-data:
  postgres-test-data:
  redis:
